### ISSUE TITLE
Nested folders

### ISSUE THREAD

**Issue by Robair996** [NicolasConstant/msfs-community-downloader#11]
Thanks for allowing to choose another folder than the Community folder. My problem is that I also use Addons linker but my aircraft are all in their own folder; I have a CJ4 folder, CRJ, A320NX etc... Could you possibly adapt the app so that one could choose a specific folder for each particular aircraft?  That would be swell. Merçi d'avance! :-)

Regarding this feature I see a problem though. Most developers advise to delete all files from a previous version before installing the new version. It seems that this would not be the way the community downloader app will be "updating". I don't know how this could be arranged. Maybe presenting the user the option " to delete" the previous version files before copying the new version files in that same folder. Is this feasible?

**Comment by NicolasConstant** [comment]
In 1.0.0 you can choose a dedicated folder of each package. 🙂
