### ISSUE TITLE
MM TBM930 update not picked up (changed filename of release)

### ISSUE THREAD

**Issue by andreas-paul** [NicolasConstant/msfs-community-downloader#34]
The recent v0.6.1 update for the TBM is not being picked up by the downloader.

The reason is likely a change in the filename associated with the TBM release: previously releases were named "aircraft-tbm-improvement.zip", while the most recent update changed this convention to "aircraft-tbm-improvement-0.6.1.zip".

![tbm_filenaming](https://user-images.githubusercontent.com/35452653/133374645-c39e36c4-812d-455b-aa5c-b474cc9d5cbe.png)

![downladertbm](https://user-images.githubusercontent.com/35452653/133374671-3b8abb39-0fce-4a24-8540-aaf39888e800.PNG)

**Comment by NicolasConstant** [comment]
Hi!
Indeed the pattern has changed and the profile has been updated accordingly, make sure you have the last version in the community packages (via "Add Package"), it will fix the issue. 🙂

![image](https://user-images.githubusercontent.com/5437247/133508863-de1b1c99-6bdc-4d77-9a18-34984d387773.png)

**Comment by andreas-paul** [comment]
Ah, I didn't know it was implemented like that! Works, thanks for the info!
