### ISSUE TITLE
Salty 747 Dev Build

### ISSUE THREAD

**Issue by Morid1n** [NicolasConstant/msfs-community-downloader#42]
Hi,

I’m trying to add the Salty 747 Dev build (https://github.com/saltysimulations/salty-747) to MSFS CD but failing. 

The latest dev build is always at https://github.com/saltysimulations/salty-747/releases/download/vdev/salty-747-dev.zip

could you help me out?

**Comment by NicolasConstant** [comment]
Yes, the tool always remove the folder entirely before copying the new files. 🙂
