### ISSUE TITLE
error importing community packages: `software too old, you ned v1.2.0 or higher`

### ISSUE THREAD

**Issue by sanromd** [NicolasConstant/msfs-community-downloader#43]
I am trying to import the new packages PMP A321-200 and PMP A330-300. The import returns the error `software too old, you ned v1.2.0 or higher`. However, the latest release is _v1.1.0_, which is installed in my system.

**Comment by NicolasConstant** [comment]
Sorry you're right, I published the package on [flightsim.to](https://flightsim.to/file/15569/msfs-community-downloader) and not here on github, it's now [fixed](https://github.com/NicolasConstant/msfs-community-downloader/releases/tag/v1.2.0).
