### ISSUE TITLE
HD B78XH DEV

### ISSUE THREAD

**Issue by baragoon** [NicolasConstant/msfs-community-downloader#46]
Hi,
Is it possible to add dev version of HD 787 mod to MSFS CD?
Thank you.

**Comment by baragoon** [comment]
Dead project or what?

**Comment by NicolasConstant** [comment]
Not dead, but as anyone I have my own life. 

Can you link to this dev version? Didn't found it on their github.

**Comment by baragoon** [comment]
> 
> 
> Not dead, but as anyone I have my own life.
> 
> Can you link to this dev version? Didn't found it on their github.

Hi! dev version of hd787x is here https://github.com/Heavy-Division/B78XH/archive/refs/heads/main.zip
I didn't get how to add with a custom path. Maybe in a future version add a possibility to put exact url for a mod.
Thank you!

**Comment by NicolasConstant** [comment]
Currently MSFS CD only support "Github Releases", so I won't be able to add this since it's a "branch" release. 
But it might be compatible in the future!
