### ISSUE TITLE
Addon continues to install in C after MSFS is moved to another drive

### ISSUE THREAD

**Issue by KaitlynnUK** [NicolasConstant/msfs-community-downloader#66]
I posted this on Discord.

Background: I moved my MSFS install from C to F due to lack of space, and afterwards MSFS seemed to be confused, in that it claimed to be installed on F, but the it was still using the Community and Official folders on C. However, I managed to sort this by moving it to E and then back to F.

The issue: However, the MSFS Community Downloader is still installing mods on C. I have uninstalled and reinstalled it several times now with no change. On checking I could see that the MSFS Community Downloader uninstall left behind a folder at C:\Users\Kaitlynn\AppData\Local\msfs-community-downloader-updater and a couple of registry entries.

I deleted these and rebooted, reinstalled, but MSFS Community Downloader is still installing mods on C whereas MSFS is reading mods from F.

Furthermore, I accidently deleted the Working Title CJ4 mod from the mods list in MSFS Community Downloader, and despite all of the above it has not returned. I also deleted the download archives and downloaded a new copy of MSFS Community Downloader  from flightsm.to and reinstalled using that, with no effect.

I'm no programmer, so please excuse my ignorance, but it seems that either there is still something in MSFS that's referring it back to C that the MSFS Community Downloader is using, or some settings for MSFS Community Downloader that are not being removed when I uninstall it.

Just to confirm, if I manually place mods in my Community folder on F, MSFS can see and use them without issue.

**Comment by NicolasConstant** [comment]
Hi! 
Like responded on discord, de tool's settings are stored in `%appdata%\msfs-community-downloader` (you can open this folder by copy-pasting it into a File Explorer window), this should reset all saved parameters.
You can also change directly the Community folder location via the Settings of the tool.

**Comment by KaitlynnUK** [comment]
Hiya,

Yeah I wasn't sure where exactly to post. :)

The ### %appdata%\msfs-community-downloader deletion worked, thank you?

May I suggest you add an option to the Uninstaller to remove this also?

**Comment by NicolasConstant** [comment]
I don't really control the installer (it's a "by default" build from the framework I use) but I'll look to it. 
Glad your issue is solved!
